[package]
name = "trezor-connect"
version.workspace = true
edition.workspace = true
description = "Rust port of trezor-connect based on THP"
license.workspace = true
repository.workspace = true
[features]
default = []
ble = ["dep:ble-transport"]
test-support = []

[dependencies]
async-trait = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
x25519-dalek = { workspace = true }
num-bigint = "0.5"
num-traits = "0.2"
hex = { workspace = true }
serde_json = { workspace = true }
ble-transport = { workspace = true, optional = true }
bs58 = { workspace = true }
thp-proto = { workspace = true }
hw-chain = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["time"] }
unicode-normalization = "0.1"
trezor-thp = { version = "0.1.1", features = ["use_std"] }
trezor-noise-rust-crypto = { version = "0.6.2", default-features = false, features = ["use-x25519", "use-aes-256-gcm", "use-sha2"] }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "test-util"] }
parking_lot = { workspace = true }
tempfile = "3"
